### ISSUE TITLE
Region Boundary Input

### ISSUE THREAD

**Issue by arthur1016** [arthur1016/hk-district-council-election-2019#3]
1. Obtain map coordinates from the map
[https://www.eac.hk/ch/distco/2019dc_elect_map.htm](https://www.eac.hk/ch/distco/2019dc_elect_map.htm)

2. Input code, name, boundary points according to empty_boundary.json as attached.
3. Further check with 反自動當選運動 FB Page to see if it is contested
[https://www.facebook.com/%E5%8F%8D%E8%87%AA%E5%8B%95%E7%95%B6%E9%81%B8%E9%81%8B%E5%8B%95-2510455555631639/](https://www.facebook.com/%E5%8F%8D%E8%87%AA%E5%8B%95%E7%95%B6%E9%81%B8%E9%81%8B%E5%8B%95-2510455555631639/)

4. region_details.json
https://docs.google.com/spreadsheets/d/1ZYyCwTT7Yyx5wDpiB8eZVadha1e4f_Tsb_jddT42YPQ/edit#gid=1304213120

**Comment by iam7seven7** [comment]
For progress and remarks please mark here:
- [x] 中西區
- [x] 灣仔區
- [x] 東區
- [x] 南區(圖一)
- [x] 油尖旺區
- [x] 南區(圖二)
- [x] 深水埗區
- [x] 九龍城區
- [x] 黃大仙區
- [x] 觀塘區
- [x] 荃灣區
- [x] 屯門區
- [x] 元朗區
- [x] 北區(圖一)
- [x] 北區(圖二)
- [x] 大埔區(圖一)
- [x] 大埔區(圖二)
- [x] 西貢區(圖一)
- [x] 西貢區(圖二)
- [x] 沙田區
- [x] 葵青區
- [x] 離島區

**Comment by iam7seven7** [comment]
@arthur1016 Seem like we can use converter: https://blog.tiger-workshop.com/hk1980-grid-to-wgs84/

Tested and it works. Open a new html file and paste this:

```
<!doctype html>
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.5.0/proj4-src.js"></script>
    <script>
        proj4.defs("EPSG:2326", "+proj=tmerc +lat_0=22.31213333333334 +lon_0=114.1785555555556 +k=1 +x_0=836694.05 +y_0=819069.8 +ellps=intl +towgs84=-162.619,-276.959,-161.764,0.067753,-2.24365,-1.15883,-1.09425 +units=m +no_defs");
        proj4.defs("EPSG:4326", "+proj=longlat +datum=WGS84 +no_defs");
        
        var result = proj4('EPSG:2326', 'EPSG:4326', [832699, 836055]);
        console.log(result);
    </script>
</head>
<body>
</body>
</html>
```

**Comment by arthur1016** [comment]
Thanks so much!!
Plan to proceed as follows:
1. Download full set of HK1980 coordinates for all Districts
2. Create convertor from HK1980 array to GPS array
3. Test when pasting into JSON

**Comment by iam7seven7** [comment]
@_@ I already did RST

Plus, boundary is pretty stable, scripting data fetching is not as urgent. I'm worrying more about updates on contestant infos we copied from spreedsheet.

Anyway, feel free to overwrite any code if it means progress 👍
